In [1]:
import pandas as pd

In [2]:
btc = pd.read_csv("data/btcusd_1-min_data.csv")

al = pd.read_csv("btc_1m_training_dataset.csv")

In [3]:
btc.head(2)

      Timestamp  Open  High   Low  Close  Volume
0  1.325412e+09  4.58  4.58  4.58   4.58     0.0
1  1.325412e+09  4.58  4.58  4.58   4.58     0.0

In [4]:
al.head(2)

,date,open,high,low,close,volume,quote_volume,trades,taker_buy_base,taker_buy_quote,...,sentiment_pos_ratio,sentiment_neg_ratio,news_count,sentiment_bull_bear,label_return_5m,label_return_15m,label_return_1h,label_dir_5m,label_dir_15m,label_dir_1h
0,2017-08-25 12:00:00,4361.27,4361.27,4261.13,4309.69,110.998609,479266.243589,1891,7.918988,34255.321811,...,0.0,0.0,1,0.0,0.021493,-0.002726,-0.006379,1,0,0
1,2017-08-25 13:00:00,4311.69,4345.00,4297.66,4312.00,20.801018,89785.160922,188,4.482264,19379.580816,...,0.0,0.0,1,0.0,0.031874,-0.003261,-0.007412,1,0,0

In [7]:
btc["Timestamp"] = pd.to_datetime(btc["Timestamp"], unit="s", utc=True) \
                    .dt.strftime("%Y.%m.%d %H:%M")

In [8]:
btc.head(2)

          Timestamp  Open  High   Low  Close  Volume
0  2012.01.01 10:01  4.58  4.58  4.58   4.58     0.0
1  2012.01.01 10:02  4.58  4.58  4.58   4.58     0.0

In [9]:
# Garder uniquement les lignes où les minutes sont "00"
btc = btc[btc["Timestamp"].str.endswith(":00")]

In [10]:
btc.head(2)

            Timestamp  Open  High   Low  Close  Volume
59   2012.01.01 11:00  4.58  4.58  4.58   4.58     0.0
119  2012.01.01 12:00  4.58  4.58  4.58   4.58     0.0